import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import "./globals.css";



export const metadata: Metadata = {
  title: "Cosmodrome Agency",
  description: "Generated by Cosmodrome Agency",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Roboto} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
